
language: elixir

elixir:
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 19.3
  - 20.0
  - 21.0

script: mix test

matrix:
  include:
    - elixir: '1.6.6'
      otp_release: '19.3'

    - elixir: '1.7.4'
      otp_release: '20.0'

    - elixir: '1.7.4'
otp_release: '21.0'
