
language: elixir

elixir:
  - 1.3
  - 1.4
  - 1.5
otp_release:
  - 17.4
  - 18.3
  - 19.3
  - 20.0

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
#     - elixir: 1.4
#       otp_release: 17.4
#     - elixir: 1.4
#       otp_release: 18.3

script: mix test